server {
    listen $PORT default_server;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api {
        proxy_pass https://selfless-simplicity-production.up.railway.app/api.php;
        proxy_set_header Host selfless-simplicity-production.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
